import { useState } from "react";
import { useWindowStore } from "@/stores";
import { Button } from "@/components/ui/button";
import { ItemCard } from "./ItemCard";
import { ChevronDown, ChevronRight, XCircle } from "lucide-react";
import type { DuplicateGroup as DuplicateGroupType } from "@/stores/types";

interface Props {
  group: DuplicateGroupType;
}

export function DuplicateGroup({ group }: Props) {
  const [collapsed, setCollapsed] = useState(false);
  const { closeDuplicates, closeWindow } = useWindowStore();

  const handleCloseGroup = async () => {
    // Pass both id and match_pattern so the backend can match the group
    // even if the UUID was regenerated by a fresh find_duplicates() call
    await closeDuplicates([group.id, group.match_pattern]);
  };

  const handleCloseItem = async (itemId: string) => {
    await closeWindow(itemId);
  };

  const matchLabel =
    group.match_type === "url_exact"
      ? "URL 完全相同"
      : group.match_type === "path_exact"
        ? "路径完全相同"
        : group.match_type === "app_title"
          ? "应用标题匹配"
          : "标题相似";

  return (
    <div className="rounded-lg border border-destructive/30 bg-destructive/5 overflow-hidden">
      {/* Group header */}
      <div className="flex items-center gap-2 px-3 py-2">
        <button
          onClick={() => setCollapsed(!collapsed)}
          className="text-muted-foreground hover:text-foreground transition-colors"
        >
          {collapsed ? (
            <ChevronRight className="w-4 h-4" />
          ) : (
            <ChevronDown className="w-4 h-4" />
          )}
        </button>

        <div className="flex-1 min-w-0">
          <span className="text-sm font-medium text-destructive">
            {group.count} 个重复
          </span>
          <span className="text-xs text-muted-foreground ml-2">
            · {matchLabel}
          </span>
          <span className="text-xs text-muted-foreground ml-2 truncate">
            · {group.match_pattern.slice(0, 40)}
          </span>
        </div>

        <Button
          variant="destructive"
          size="sm"
          onClick={handleCloseGroup}
        >
          <XCircle className="w-3.5 h-3.5 mr-1" />
          关闭 {group.count - 1} 个
        </Button>
      </div>

      {/* Items */}
      {!collapsed && (
        <div className="border-t border-destructive/20">
          {group.items.map((item, idx) => (
            <div key={item.id} className="relative">
              <ItemCard item={item} />
              {/* "Keep this" indicator for first item */}
              {idx === 0 && (
                <span className="absolute right-2 top-1/2 -translate-y-1/2 text-[10px] text-muted-foreground bg-background/80 px-1.5 py-0.5 rounded">
                  保留
                </span>
              )}
              {/* Close this single item */}
              {idx > 0 && (
                <button
                  onClick={(e) => {
                    e.stopPropagation();
                    handleCloseItem(item.id);
                  }}
                  className="absolute right-2 top-1/2 -translate-y-1/2 text-[10px] text-destructive/70 hover:text-destructive bg-background/80 px-1.5 py-0.5 rounded transition-colors"
                >
                  关闭此项
                </button>
              )}
            </div>
          ))}
        </div>
      )}
    </div>
  );
}